### ISSUE TITLE
Consider replacing Makefile with a shell script

### ISSUE THREAD

**Issue by akauppi** [lure23/EmbeddedRover#4]
Once things are stable:

- just `prep.sh` [`purge|shell`]

+ Move documentation to `docs` branch so what one sees is what one uses, for their own project.

**Comment by lure23** [comment]
Also cover ssh key copying automatically.

$ sudo cp "/var/root/Library/Application Support/multipassd/ssh-keys/id_rsa" .mp/multipassd.key
$ sudo chown .mp/multipassd.key {your-username}
$ sudo chmod a+r .mp/multipassd.key

**Comment by lure23** [comment]
done
